#Docker image
image:
  file: .gitpod.dockerfile
  context: apache

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
- name: Terminal
  command: >
    echo "Installing Composer"
    composer install;
- name: Apache
  command: >
    echo "Starting Apache"
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log;

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart





