#Docker image
image:
  file: .gitpod.dockerfile
  context: apache

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
- port: 8080
  onOpen: open-preview

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
- name: Terminal
  command: >
    echo "Install Composer";
    composer install;
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
- name: Mysql
  command: >
    mysql -u root -p nzbitcoiners < example.sql

    
